# 02.4 선형 연립방정식과 역행렬
- https://datascienceschool.net/view-notebook/927d7f7972dd434ead9d294169ae7f34/

In [1]:
import numpy as np

In [18]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])

In [20]:
Ainv = np.linalg.inv(A)

In [19]:
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [21]:
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [22]:
Ainv@A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
A@Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [25]:
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [26]:
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [29]:
b = np.array([[2],[4],[1]])

In [30]:
Ainv@b

array([[-3.],
       [ 5.],
       [-1.]])

In [32]:
x, resid, rank, s = np.linalg.lstsq(A,b)

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [33]:
rank

3

In [34]:
s

array([2.41421356, 1.        , 0.41421356])

In [35]:
resid

array([], dtype=float64)

In [36]:
x

array([[-3.],
       [ 5.],
       [-1.]])

In [37]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [42]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [41]:
b

array([24. , 21.6, 34.7, 33.4])

In [43]:
np.linalg.lstsq(A,b)

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01]),
 array([], dtype=float64),
 4,
 array([1.28391009e+02, 2.97333579e+00, 7.58898410e-02, 7.51932881e-03]))

In [45]:
len(X)

506

In [46]:
len(y)

506

In [48]:
X.shape

(506, 13)

In [50]:
np.linalg.lstsq(X,y)

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
        -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
         1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
        -4.16304471e-01]),
 array([12228.04626104]),
 13,
 array([1.25851816e+04, 3.44597406e+03, 6.45757109e+02, 4.02050461e+02,
        1.58964612e+02, 1.21502936e+02, 9.04652420e+01, 7.79311708e+01,
        6.50828345e+01, 2.46251803e+01, 1.80945451e+01, 5.51505065e+00,
        1.48096916e+00]))